// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"github.com/rn-consider/gormgenex/dao/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.Tag{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Tag{}) fail: %s", err)
	}
}

func Test_tagQuery(t *testing.T) {
	tag := newTag(db)
	tag = *tag.As(tag.TableName())
	_do := tag.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(tag.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <tags> fail:", err)
		return
	}

	_, ok := tag.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from tag success")
	}

	err = _do.Create(&model.Tag{})
	if err != nil {
		t.Error("create item in table <tags> fail:", err)
	}

	err = _do.Save(&model.Tag{})
	if err != nil {
		t.Error("create item in table <tags> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Tag{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <tags> fail:", err)
	}

	_, err = _do.Select(tag.ALL).Take()
	if err != nil {
		t.Error("Take() on table <tags> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <tags> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <tags> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <tags> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Tag{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <tags> fail:", err)
	}

	_, err = _do.Select(tag.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <tags> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <tags> fail:", err)
	}

	_, err = _do.Select(tag.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <tags> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <tags> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <tags> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <tags> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Tag{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <tags> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <tags> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <tags> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <tags> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <tags> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <tags> fail:", err)
	}
}
