// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArticleTag = "articles_tags"

// ArticleTag mapped from table <article_tags>
type ArticleTag struct {
	ArticleID int32 `gorm:"column:article_id;type:int;primaryKey" json:"articleId"`
	TagID     int32 `gorm:"column:tag_id;type:int;primaryKey;index:tag_id,priority:1" json:"tagId"`
}

// TableName ArticleTag's table name
func (*ArticleTag) TableName() string {
	return TableNameArticleTag
}

