// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserInfo = "user_infos"

// UserInfo mapped from table <user_infos>
type UserInfo struct {
	UserID int32  `gorm:"column:user_id;type:int;index:user_id,priority:1" json:"user_id"`
	ID     int32  `gorm:"column:id;type:int;primaryKey" json:"id"`
	Addr   string `gorm:"column:addr;type:varchar(255)" json:"addr"`
}

// TableName UserInfo's table name
func (*UserInfo) TableName() string {
	return TableNameUserInfo
}
