// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

type User struct {
	ID   uint 
	Name string
}
// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
